apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  app.subhakarkotta.com/datacenter: dc2
patchesStrategicMerge:
  - deployment_patch.yaml
resources:
  - https://github.com/alaghusundhar/hello-kubernetes-dev-config/base/?ref=v2.1
